# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alex-hollander.com
title: Personal Site
email: alexhollander522@gmail.com
author: Alex Hollander
description: > # "Write an awesome description for your new site here. 
          I've been programming games in the Unity game engine for the last 5 years. 
          Some of my games have one awards, but most haven't seen the light of day. 
          I'm interested in data science, and more 
          specifically bioinformatics, functional programming,
          AI, Shaders, cats, and local Philly lore. 
copyright: 'Copyright &copy; 2018 Alex Hollander. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/_vaults
  - title: github
    url: https://github.com/Ashen-Vaults
  - title: linkedin
    url: https://linkedin.com/alexhollander522
