# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alex-hollander.com
title: Unity Dev | Data Scientist
email: alexhollander522@gmail.com
author: Alex Hollander
description: > # "Write an awesome description for your new site here. 
          I've been programming games in the Unity game engine for the last 5 years. 
          Some of my games have one awards, but most haven't seen the light of day. 
          I'm interested in data science, and more 
          specifically bioinformatics, functional programming,
          AI, Shaders, cats, and local Philly lore. 
copyright: 'Copyright &copy; 2018 Alex Hollander. All Rights Reserved.'
credits: Alex Hollander

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-hacker

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ashen_vaults
  - title: github
    url: https://github.com/Ashen-Vaults
  - title: linkedin
    url: https://www.linkedin.com/in/alexhollander522/



github: [metadata]